### ISSUE TITLE
Create template for Pull Requests

### ISSUE THREAD

**Issue by kairoaraujo** [in-toto/archivista#110]
The idea is to add the `.github/PULL_REQUESTS` with a template for new contributors.
It will help improve the quality of contributions and guide the contributors to avoid misinformation.
The maintainers will have better information to improve and speed up the review.

#### Parent issue
- [ ] #105

**Comment by kairoaraujo** [comment]
Thank you, @prashantrewar, for your interest in contributing. 
I assigned the issue to you. Let me know if you have any questions. 

I think this witness PR is a good reference. 

https://github.com/in-toto/witness/pull/351

**Comment by prashantrewar** [comment]
Thank you @kairoaraujo for assigning and guidance. I will let you know if I have questions

**Comment by prashantrewar** [comment]
@kairoaraujo I created a PR for this issue, could you please take a look?
