### ISSUE TITLE
Move https://github.com/testifysec/charts into the Archivista Repository

### ISSUE THREAD

**Issue by kairoaraujo** [in-toto/archivista#126]
Move https://github.com/testifysec/charts into the Archivista Repository.

It also should be documented in the [Archivista Guide](#111) in a "Deployment" section.
Give the user information about deployment, scalability, and high availability.

**Comment by matglas** [comment]
Discussed this and it decision was to put the original chart from testifysec/carts into a chart folder in the archivista repo and update the readme with Deployment section.
