### ISSUE TITLE
Handle migrations

### ISSUE THREAD

**Issue by mikhailswift** [in-toto/archivista#42]
Sometimes we add the ability to scrape additional metadata from attestations, but we currently don't have a good way to load in the new data about attestations already in Archivist.

Currently this hasn't been of high priority since it's all dev data and in the past when I've wanted to collect metadata from existing attestations I've just wiped Archivist's database and re-loaded all of the attestations from the bucket. This is obviously not a great way to do this.

We may be able to tie into ent's Atlas integration to handle some of these migrations:

https://entgo.io/docs/migrate/#atlas-integration

**Comment by kairoaraujo** [comment]
Closed by
- #125
